apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-client
  template:
    metadata:
      labels:
        app: ticketing-client
    spec:
      containers:
        - name: ticketing-client
          image: stanvasilyev/ticketing_client
          env:
            - name: INGRESS_BASE_URL
              value: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-client-srv
spec:
  type: ClusterIP
  selector:
    app: ticketing-client
  ports:
    - name: ticketing-client
      protocol: TCP
      port: 3000
      targetPort: 3000
