apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-auth
  template:
    metadata:
      labels:
        app: ticketing-auth
    spec:
      containers:
        - name: ticketing-auth
          image: stanvasilyev/ticketing_auth
          # image: us.gcr.io/ticketing-node-js-course/ticketing_auth
          env:
            - name: MONGO_URI
              value: "mongodb://ticketing-auth-mongo-srv:27017/ticketing_auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-auth-srv
spec:
  type: ClusterIP
  selector:
    app: ticketing-auth
  ports:
    - name: ticketing-auth
      protocol: TCP
      port: 3000
      targetPort: 3000
