apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-payments
  template:
    metadata:
      labels:
        app: ticketing-payments
    spec:
      containers:
        - name: ticketing-payments
          image: stanvasilyev/ticketing_payments
          # image: us.gcr.io/ticketing-node-js-course/ticketing_auth
          env:
            - name: MONGO_URI
              value: "mongodb://ticketing-payments-mongo-srv:27017/ticketing_payments"
            - name: NATS_URL
              value: "http://ticketing-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payments-srv
spec:
  type: ClusterIP
  selector:
    app: ticketing-payments
  ports:
    - name: ticketing-payments
      protocol: TCP
      port: 3000
      targetPort: 3000
